CREATE DATABASE IF NOT EXISTS crud_node CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE crud_node;

CREATE TABLE IF NOT EXISTS alunos (
    id INT NOT NULL AUTO_INCREMENT,
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(100) NOT NULL,
    curso VARCHAR(40),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updates_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);