version: '3'
networks: 
    db_net:
services:
  app:
    image: node:10.24.1-slim
    volumes:
      - ./app:/app
    working_dir: /app
    ports:
      - 81:3000
    networks:
      - db_net
    environment:
      - DB_IP=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
    command: bash -c "npm install && npm run production"
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./app/database/init.sql:/data/application/init.sql
      - ./db:/var/lib/mysql
    command: --init-file /data/application/init.sql
    networks:
      - db_net
    environment:
      - MYSQL_ROOT_PASSWORD=root